import { join } from 'node:path';
import { writeFile } from 'node:fs/promises';

import type { Nitro } from 'nitropack/types';
import { defineNuxtModule } from 'nuxt/kit';

// Module options TypeScript interface definition
export interface ModuleOptions {}

type Unimport = Nitro['unimport'];

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-oxc',
    configKey: 'oxc',
  },
  // Default configuration options of the Nuxt module
  defaults: {},
  setup(_options, nuxt) {
    let unImport: Unimport | undefined;
    let nitroUnImport: Unimport | undefined;

    nuxt.hook('imports:context', (context: Unimport) => {
      unImport = context;
    });

    // oxlint-disable-next-line
    // @ts-ignore - weird bug with tsgo
    nuxt.hook('nitro:init', (nitro: Nitro) => {
      nitroUnImport = nitro.unimport;
    });

    nuxt.hook('builder:generateApp', async () => {
      const unImports = await Promise.all([unImport?.getImports(), nitroUnImport?.getImports()].filter((i) => !!i));

      const sortedImports = unImports
        .flat()
        .sort((a, b) => 10 * a.from.localeCompare(b.from) + a.name.localeCompare(b.name))
        .map((i) => i.as ?? i.name);

      sortedImports.unshift('defineNuxtConfig');
      const globals = Object.fromEntries(sortedImports.map((i) => [i, 'readonly'] as const));

      const code = [
        `// This file is auto-generated by the oxc Nuxt module. Do not edit it manually.`,
        `import type { OxlintGlobals } from 'oxlint';`,
        `export const globals: OxlintGlobals = ${JSON.stringify(globals, null, 2)};`,
      ].join('\n\n');

      await writeFile(join(nuxt.options.buildDir, 'oxlint.globals.ts'), code, 'utf-8');
    });
  },
});
